# Generated by Django 2.2 on 2020-06-26 11:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('nickname', models.CharField(max_length=30)),
                ('phone_number', models.CharField(max_length=20)),
                ('sex', models.IntegerField(blank=True, choices=[(1, 'male'), (2, 'female')], null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_number', models.CharField(max_length=12)),
                ('product_name', models.CharField(max_length=100)),
                ('dt_order', models.DateTimeField(auto_now_add=True)),
                ('buyer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', related_query_name='order', to='api.Profile')),
            ],
        ),
    ]
