# Generated by Django 2.2 on 2020-06-26 14:52

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20200626_1424'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='created_time',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='profile',
            name='modified_time',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
